spring:
  application.name: ichiro-family-tree
  config.import: optional:file:.env[.properties] # enable scanning of .env file for environment variables
server.port: 5000 # Elastic Beanstalk port

springdoc:
  swagger-ui.path: swagger-ui
  api-docs.path: /${spring.application.name}
  paths-to-match: /api/**

api.key:
  header: api-key
  value: ${API_KEY}