server.port: 8080

spring:
  profiles.active: ${IFT_PROFILE:prod}
  application.name: ichiro-family-tree
  config.import: optional:file:.env[.properties] # enable scanning of .env file for environment variables

springdoc:
  swagger-ui.path: swagger-ui
  api-docs.path: /${spring.application.name}
  paths-to-match: /api/**

api.key:
  header: api-key
  value: ${IFT_API_KEY}

---
spring:
  config.activate.on-profile: dev
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS ICHIRO\;
    username: sa
    password:
  h2.console.enabled: true
---
spring:
  config.activate.on-profile: prod
  jpa:
    database: Oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@ichiro_high
    username: ICHIRO
    password: ${DB_PASSWORD}
