spring:
  application:
    name: ichiro-family-tree

springdoc:
  swagger-ui.path: swagger-ui
  api-docs.path: /${spring.application.name}
  paths-to-match: /api/v1/**, /v1/**

page:
  url: http://www.shiba-pedigree.ru/details.php?id=79238
  selector: '#pedigree > tbody'
