spring:
  application:
    name: ichiro-family-tree
server:
  port: 5000

springdoc:
  swagger-ui.path: swagger-ui
  api-docs.path: /${spring.application.name}
  paths-to-match: /api/v1/**, /v1/**

page:
  url: 'http://www.shiba-pedigree.ru/'
  ichiro-profile: 'details.php?id=79238'
  selector: '#pedigree > tbody'
